- hosts: all
  tasks:
    - name: Create a user with password authentication
      user:
        name: insecure_user
        password: "{{ 'password123' | password_hash('sha512') }}"  
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Allow passwordless sudo
      lineinfile:
        path: /etc/sudoers
        line: 'insecure_user ALL=(ALL) NOPASSWD:ALL'  