name: "Frogbot Scan and Fix"
on:
  push:
    branches: [ "main"]
permissions:
  contents: write
  pull-requests: write
  security-events: write

jobs:
  create-fix-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GH_TOKEN }}
     
