name: JFrog Xray IaC Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JFrog CLI
        run: |
          curl -fL https://install-cli.jfrog.io | sh
          jf --version

      - name: Configure JFrog CLI
        env:
          JFROG_URL: ${{ vars.JFROG_URL }}
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_PASSWORD: ${{ secrets.JFROG_ACCESS_TOKEN }} # Changed from JF_ACCESS_TOKEN to JFROG_PASSWORD
        run: |
          jf c add myJFrogServer --url=$JFROG_URL --user=$JFROG_USER --password=$JFROG_ACCESS_TOKEN --interactive=false
          jf c use myJFrogServer

      - name: Verify JFrog CLI Configuration
        run: jf c show

      - name: Run JFrog Xray Scan
        run: jf scan .
