name: JFrog Xray & Checkov IaC Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  upload-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install JFrog CLI
        run: |
          curl -fL https://install-cli.jfrog.io | sh
          jf --version

      - name: Configure JFrog CLI
        env:
          JFROG_URL: ${{ vars.JFROG_URL }}
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        run: |
          jf c add myJFrogServer --url=jf c add myJFrogServer --url=$JFROG_URL --user=$JFROG_USER --password=$JFROG_PASSWORD --interactive=false --user=$JFROG_USER --password=$JFROG_PASSWORD --interactive=false
          jf c use myJFrogServer

      - name: Upload IaC Files to Artifactory
        run: |
          jf rt upload "*.tf" https://infomagnus.jfrog.io/artifactory/api/generic/iac-repository
          jf rt upload "*.yaml" https://infomagnus.jfrog.io/artifactory/api/generic/iac-repository
          jf rt upload "*.yml" https://infomagnus.jfrog.io/artifactory/api/generic/iac-repository
          jf rt upload "*.json" https://infomagnus.jfrog.io/artifactory/api/generic/iac-repository
          jf rt upload "charts/*.tgz" https://infomagnus.jfrog.io/artifactory/api/generic/iac-repository

      - name: Run Checkov IaC Security Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform,kubernetes,ansible,helm
        continue-on-error: true  # Allows the workflow to proceed even if vulnerabilities are found

      - name: Run JFrog Xray Scan
        run: jf scan iac-repository/
        continue-on-error: true  # Ensures that the scan runs even if previous steps report vulnerabilities
